---
- name: Ensure containers configuration is applied
  ansible.builtin.template:
    src: containers.conf.j2
    dest: /etc/containers/containers.conf
    owner: root
    group: root
    mode: '0644'

- name: Ensure registries configuration is applied
  ansible.builtin.template:
    src: registries.conf.j2
    dest: /etc/containers/registries.conf
    owner: root
    group: root
    mode: '0644'